using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using TestingSystems.App_Data;

namespace TestingSystems
{
    public class MenuHelper
    {
        public class MenuIdentityCodes
        {
            public const string Order = "Order";
            public const string CustomerMaster = "CustomerMaster";

            //Properties For Getter setter for Menu Started

            public const string CUSTOMERMASTER = "_CUSTOMERMASTER";
            public const string SUPPLIERMASTER = "_SUPPLIERMASTER";
            public const string DIEMASTER = "_DIEMASTER";
            public const string PATTERNMASTER = "_PATTERNMASTER";
            public const string CASTINGMASTER = "_CASTINGMASTER";
            public const string PURCHASEITEM = "_PURCHASEITEM";
            public const string FOUNDRYRETURNSMASTER = "_FOUNDRYRETURNSMASTER";
            public const string METALMASTER = "_METALMASTER";
            public const string METALELEMENTMASTER = "_METALELEMENTMASTER";
            public const string CHARGEMASTER = "_CHARGEMASTER";
            public const string OTHERMASTERS = "_OTHERMASTERS";
            public const string MACHINEMASTER = "_MACHINEMASTER";
            public const string STATECITYMASTER = "_STATECITYMASTER";
            public const string TCTEMPLATEMASTER = "_TCTEMPLATEMASTER";
            public const string UOMMASTER = "_UOMMASTER";
            public const string PROCESSMASTER = "_PROCESSMASTER";
            public const string PREFIXMASTER = "_PREFIXMASTER";
            public const string OPERATORMASTER = "_OPERATORMASTER";
            public const string REJECTIONREASONMASTER = "_REJECTIONREASONMASTER";
            public const string USERMASTER = "_USERMASTER";
            public const string CUSTOMERORDER = "_CUSTOMERORDER";
            public const string RAWMATERIALINWARD = "_RAWMATERIALINWARD";
            public const string MATERIALISSUE = "_MATERIALISSUE";
            public const string MODIFYSTOCKRM = "_MODIFYSTOCKRM";
            public const string MODIFYSTOCKFG = "_MODIFYSTOCKFG";
            public const string PRODUCTIONENTRY = "_PRODUCTIONENTRY";
            public const string PRODUCTIONENTRYSAND = "_PRODUCTIONENTRYSAND";
            public const string REJECTIONENTRY = "_REJECTIONENTRY";
            public const string CONSUMPTIONENTRY = "_CONSUMPTIONENTRY";
            public const string FOUNDRYRETUNENTRY = "_FOUNDRYRETUNENTRY";
            public const string DISPATCHENTRY = "_DISPATCHENTRY";
            public const string CUSTOMERRETURNENTRY = "_CUSTOMERRETURNENTRY";
            public const string INWARDREJECTION = "_INWARDREJECTION";
            public const string INHOUSEREJECTION = "_INHOUSEREJECTION";
            public const string CUSTOMERREJECTION = "_CUSTOMERREJECTION";
            public const string CONVERTREJECTIONTORM = "_CONVERTREJECTIONTORM";
            public const string CUSTOMERREGISTER = "_CUSTOMERREGISTER";
            public const string SUPPLIERREGISTER = "_SUPPLIERREGISTER";
            public const string DIEREGISTER = "_DIEREGISTER";
            public const string PATTERNREGISTER = "_PATTERNREGISTER";
            public const string CASTINGREGISTER = "_CASTINGREGISTER";
            public const string PURCHASEITEMREGISTER = "_PURCHASEITEMREGISTER";
            public const string FOUNDRYRETURNMASTER = "_FOUNDRYRETURNMASTER";
            public const string RAWMATERIALINWARDREGISTR = "_RAWMATERIALINWARDREGISTR";
            public const string MATERIALISSUEREGISTER = "_MATERIALISSUEREGISTER";
            public const string INVENTORYREGISTERFG = "_INVENTORYREGISTERFG";
            public const string INVENTORYREGISTERRM = "_INVENTORYREGISTERRM";
            public const string CUSTOMERORDERREGISTER = "_CUSTOMERORDERREGISTER";
            public const string PRODUCTIONREGISTER = "_PRODUCTIONREGISTER";
            public const string PRODUCTIONREGISTERSAND = "_PRODUCTIONREGISTERSAND";
            public const string CONSUMPTIONREGISTER = "_CONSUMPTIONREGISTER";
            public const string FOUNDRYRETURNREGISTER = "_FOUNDRYRETURNREGISTER";
            public const string DISPATCHREGISTER = "_DISPATCHREGISTER";
            public const string CUSTOMERRETURNREGISTER = "_CUSTOMERRETURNREGISTER";
            public const string PRODUCTIONREPORT = "_PRODUCTIONREPORT";
            public const string DAILYPRODUCTION = "_DAILYPRODUCTION";
            public const string MELTINGSUMMARYREPORT = "_MELTINGSUMMARYREPORT";
            public const string REASONWISEREJECTION = "_REASONWISEREJECTION";
            public const string PENDINGPRODUCTION = "_PENDINGPRODUCTION";
            public const string CHANGEPASSWORD = "_CHANGEPASSWORD";
            public const string SCREENSHARE = "_SCREENSHARE";
            public const string DELIVERYSTATUS = "_DELIVERYSTATUS";
            public const string DAILYPRODUCTIONREPORTSAND = "_DAILYPRODUCTIONREPORTSAND";
            public const string FGRate = "_FGRate";
            public const string RMRate = "_RMRate";
            public const string TerrifCodeMaster = "_TerrifCodeMaster";
            public const string MaterialInspectionMappings = "_MATERIALINSPECTIONMAPPING";
            public const string PURCHASEORDERMASTER = "_PURCHASEORDERMASTER";
            public const string PURCHASERETURNGST = "_PURCHASERETURNGST";
            public const string TaxMaster = "_TaxMaster";
            public const string SALESINVOICE = "_SALESINVOICE";
            public const string SALESINVOICEGST = "_SALESINVOICEGST";
            public const string PURCHASEORDERREGISTER = "_PURCHASEORDERREGISTER";
            public const string DIRECTTESTCERTIFICATE = "_DIRECTTESTCERTIFICATE";
            public const string REJECTIONREGISTER = "_REJECTIONREGISTER";
            public const string TESTCERTIFICATEREGISTER = "_TESTCERTIFICATEREGISTER";
            public const string SCRAPANDFERROALLOYINSPECTIONREGISTER = "_SCRAPANDFERROALLOYINSPECTIONREGISTER";
            public const string CONVERTEDREJECTIONREGISTER = "_CONVERTEDREJECTIONREGISTER";
            public const string MANAGEREJECTIONREGISTER = "_MANAGEREJECTIONREGISTER";
            public const string JOBWORKLOSSINWARDREGISTER = "_JOBWORKLOSSINWARDREGISTER";
            public const string EVALUTIONSHEET = "_EVALUTIONSHEET";
            public const string CHARTS = "_CHARTS";
            public const string DASHBOARDCHART = "_DASHBOARDCHART";
            public const string RATECONTRACT = "_RATECONTRACT";
            public const string RATECONTRACTREGISTER = "_RATECONTRACTREGISTER";
            public const string INDENTMASTER = "_INDENTMASTER";
            public const string INDENTREGISTER = "_INDENTREGISTER";
            public const string SCHEDULEDDELIVERIES = "_SCHEDULEDDELIVERIES";
            public const string INQUIRY = "_INQUIRY";
            public const string BUSINESSANALYSIS = "_BUSINESSANALYSIS";
            public const string SERVICEITEMMASTER = "_SERVICEITEMMASTER";
            public const string SERVICEITEMREGISTER = "_SERVICEITEMREGISTER";
            public const string INDENTWISEPOREGISTER = "_INDENTWISEPOREGISTER";
            public const string JOBWORKOUT = "_JOBWORKOUT";
            public const string JOBWORKLOSSINWARD = "_JOBWORKLOSSINWARD";
            public const string JOBOUTREGISTER = "_JOBOUTREGISTER";
            public const string INQUIRYREGISTER = "_INQUIRYREGISTER";
            public const string PURCHASEINVOICE = "_PURCHASEINVOICE";
            public const string PURCHASEINVOICEGST = "_PURCHASEINVOICEGST";
            public const string PURCHASEINVOICEREGISTER = "_PURCHASEINVOICEREGISTER";
            public const string INHOUSEPROCESS = "_INHOUSEPROCESS";
            public const string CHECKFORUPDATES = "_CHECKFORUPDATES";
            public const string JOBRETURN = "_JOBRETURN";
            public const string JOBRETURNREGISTER = "_JOBRETURNREGISTER";
            public const string COSTEVALUTIONREGISTER = "_COSTEVALUTIONREGISTER";
            public const string INHOUSESTOCKTRANSFERREGISTER = "_PROCESSSTOCKTRANSFERREGISTER";
            public const string QUOTATION = "_QUOTATION";
            public const string CASTINGPURCHASEINWARD = "_CASTINGPURCHASEINWARD";
            public const string CASTINGPURCHASEINWARDREGISTER = "_CASTINGPURCHASEINWARDREGISTER";
            public const string MOLDBOXMASTER = "_MOLDBOXMASTER";
            public const string SANDTYPEMASTER = "_SANDTYPEMASTER";
            public const string HEATPROPERTIES = "_HEATPROPERTIES";
            public const string PREFIXSUFFIX = "_PREFIXSUFFIX";
            public const string QUOTATIONREGISTER = "_QUOTATIONREGISTER";
            public const string CASTINGMOLDBOXMASTER = "_CASTINGMOLDBOXMASTER";
            public const string CASTINGRATEHISTORY = "_CASTINGRATEHISTORY";
            public const string CASTINGTRANSACTION = "_CASTINGTRANSACTION";
            public const string STOCKTRANSACTION = "_STOCKTRANSACTION";
            public const string INVENTORY = "_INVENTORY";
            public const string CASTHISTORY = "_CASTHISTORY";
            public const string PATTERNISSUE = "_PATTERNISSUE";
            public const string PATTERNISSUEREGISTER = "_PATTERNISSUEREGISTER";
            public const string CUSTOMTEXT = "_CUSTOMTEXT";
            public const string PATTERNRETURN = "_PATTERNRETURN";
            public const string PATTERNRETURNREGISTER = "_PATTERNRETURNREGISTER";
            public const string ReportAveragePurchaseRate = "_ReportAveragePurchaseRate";
            public const string TAXTEMPLATE = "_TAXTEMPLATE";
            public const string ACCESSMENU = "_ACCESSMENU";
            public const string MASTERUPLOAD = "_MASTERUPLOAD";
            public const string RAWMATERIALREJECTION = "_RAWMATERIALREJECTION";
            public const string RAWMATERIALREJECTIONREGISTER = "_RAWMATERIALREJECTIONREGISTER";
            public const string PATTERNTRANSACTIONREPORT = "_PATTERNTRANSACTIONREPORT";
            public const string REJECTIONREPORT = "_REJECTIONREPORT";
            public const string HeatPropertiesRegister = "_HEATPROPERTIESREGISTER";
            public const string SETMASTER = "_SETMASTER";
            public const string SETREGISTER = "_SETREGISTER";
            public const string EQUIPMENT = "_EQUIPMENT";
            public const string EQUIPMENTREGISTER = "_EQUIPMENTREGISTER";
            public const string AMCMASTER = "_AMCMASTER";
            public const string AMCREGISTER = "_AMCREGISTER";
            public const string CALIBRATIONDETAIL = "_CALIBRATIONDETAIL";
            public const string CALIBRATIONREGISTER = "_CALIBRATIONREGISTER";
            public const string PREVENTIVEMASTER = "_PREVENTIVEMASTER";
            public const string CALIBRATIONDUE = "_CALIBRATIONDUE";
            public const string BREAKDOWN = "_BREAKDOWN";
            public const string BREAKDOWNREGISTER = "_BREAKDOWNREGISTER";
            public const string SERVICEENTRY = "_SERVICEENTRY";
            public const string SERVICEENTRYREGISTER = "_SERVICEENTRYREGISTER";
            public const string PREVENTIVEMASTERREGISTER = "_PREVENTIVEMASTERREGISTER";
            public const string PREVENTIVEMAINTENANCEDUE = "_PREVENTIVEMAINTENANCEDUE";
            public const string ISONUMBERING = "_ISONUMBERING";
            public const string PRODUCTIONSET = "_PRODUCTIONSET";
            public const string PRODUCTIONSETREGISTER = "_PRODUCTIONSETREGISTER";
            public const string CURRENCYEXCHANGE = "_CURRENCYEXCHANGE";
            public const string EXPORTINVOICEREGISTER = "_EXPORTINVOICEREGISTER";
            public const string CONVERTITEMENTRY = "_CONVERTITEMENTRY";
            public const string REPORTINVENTORYPROCESSWISECASTCODEWISE = "_REPORTINVENTORYPROCESSWISECASTCODEWISE";
            public const string REPORTCUSTOMERWISESTOCKBREAKUP = "_REPORTCUSTOMERWISESTOCKBREAKUP";
            public const string REPORTCUSTOMERWISECASTINGWISESTOCKBREAKUP = "_REPORTCUSTOMERWISECASTINGWISESTOCKBREAKUP";
            public const string REPORTSETRATEHISTORY = "_REPORTSETRATEHISTORY";
            public const string CONTRACTMASTER = "_CONTRACTMASTER";
            public const string CONTRACTREGISTER = "_CONTRACTREGISTER";
            public const string CONTRACTENTRY = "_CONTRACTENTRY";
            public const string CUSTOMERPATTERNRETURN = "_CUSTOMERPATTERNRETURN";
            public const string REPORTCONTRACTORWISEAMOUNTBREAKUP = "_REPORTCONTRACTORWISEAMOUNTBREAKUP";
            public const string CUSTOMERPATTERNRETURNREGISTER = "_CUSTOMERPATTERNRETURNREGISTER";
            public const string PATTERNLOG = "_PATTERNLOG";
            public const string PENDINGINSPECTIONREPORT = "_PENDINGINSPECTIONREPORT";
            public const string PENDINGREJECTION = "_PENDINGREJECTION";
            public const string PENDINGRETURNREPORT = "_PENDINGRETURNREPORT";
            public const string SUPERVISORMASTER = "_SUPERVISORMASTER";
            public const string CASTINGWISEGRADEPROPERTYMASTER = "_CASTINGWISEGRADEPROPERTYMASTER";
            public const string SCRAPANDFERROALLOYINSPECTION = "_SCRAPANDFERROALLOYINSPECTION";
            
            public const string TC = "_TC";
            public const string MOLDINGENTRY = "_MOLDINGENTRY";
            public const string MOLDINGCAVITYENTRY = "_MOLDINGCAVITYENTRY";
            public const string MOLDINGENTRYREGISTER = "_MOLDINGENTRYREGISTER";
            public const string MOLDINGCAVITYENTRYREGISTER = "_MOLDINGCAVITYENTRYREGISTER";
            public const string POURINGENTRY = "_POURINGENTRY";
            public const string REPORTPURCHASEITEMWISESTOCKBREAKUP = "_REPORTPURCHASEITEMWISESTOCKBREAKUP";
            public const string PLANNING = "_PLANNING";
            public const string PLANNINGREGISTER = "_PLANNINGREGISTER";
            public const string REPORTPLANNINGVSACTUAL = "_REPORTPLANNINGVSACTUAL";
            public const string FURNACEANDSHIFTMASTER = "_FURNACEANDSHIFTMASTER";
            public const string COMPANYMASTER = "_COMPANYMASTER";
            public const string MULTIPLERATECONTRACT = "_MULTIPLERATECONTRACT";
            public const string DRAWINGNOMASTER = "_DRAWINGNOMASTER";
            public const string REPORTMOLDING = "_REPORTMOLDING";
            public const string PROCESSWISEREJECTIONREPORT = "_PROCESSWISEREJECTIONREPORT";
            public const string PENDINGORDERREPORT = "_PENDINGORDERREPORT";
            public const string MONTHWISEORDERCHART = "_MONTHWISEORDERCHART";
            public const string MONTHWISESALESCHART = "_MONTHWISESALESCHART";
            public const string MONTHWISEORDERANDSALESCOMPCHART = "_MONTHWISEORDERANDSALESCOMPCHART";
            public const string TOPSUPPLIERBYAMOUNT = "_TOPSUPPLIERBYAMOUNT";
            public const string METALGROUPWISESALES = "_METALGROUPWISESALES";
            public const string COSTINGREPORT = "_COSTINGREPORT";
            public const string REMINDER = "_REMINDER";
            public const string MOLDERWISECASTINGREJECTIONREPORT = "_MOLDERWISECASTINGREJECTIONREPORT";
            public const string CUSTOMERWISECASTINGDETAIL = "_CUSTOMERWISECASTINGDETAIL";
            public const string HEATWISEPOURINGREOPRT = "_HEATWISEPOURINGREOPRT";
            public const string MONTHWISEPRODUCTIONDETAILREPORT = "_MONTHWISEPRODUCTIONDETAILREPORT";
            public const string INCOMINGINSPECTIONREPORT = "_INCOMINGINSPECTIONREPORT";
            public const string MONTHWISEMACHININGANDINHOUSEREJECTION = "_MONTHWISEMACHININGANDINHOUSEREJECTION";
            public const string MOLDOPENINGSTOCK = "_MOLDOPENINGSTOCK";
            public const string COSTINGCATEGORY = "_COSTINGCATEGORY";
            public const string COSTINGCATEGORYENTRY = "_COSTINGCATEGORYENTRY";
            public const string REPORTITEMWISESALESDETAIL = "_REPORTITEMWISESALESDETAIL";
            public const string COREPRODUCTION = "_COREPRODUCTION";
            public const string COREPRODUCTIONREGISTER = "_COREPRODUCTIONREGISTER";
            public const string COREOPENINGSTOCK = "_COREOPENINGSTOCK";
            public const string MOLDINGREJECTIONENTRY = "_MOLDINGREJECTIONENTRY";
            public const string MOLDINGREJECTIONREGISTER = "_MOLDINGREJECTIONREGISTER";
            public const string COREREJECTIONENTRY = "_COREREJECTIONENTRY";
            public const string COREREJECTIONREGISTER = "_COREREJECTIONREGISTER";
            public const string CHARGEPROPERTYMASTER = "_CHARGEPROPERTYMASTER";
            public const string REPORTJOBWORKITEM = "_REPORTJOBWORKITEM";
            public const string SANDTYPEREJECTION = "_SANDTYPEREJECTION";
            public const string HEATWISEINVENTORYREPORT = "_HEATWISEINVENTORYREPORT";
            public const string CUSTOMERREJECTIONREGISTER = "_CUSTOMERREJECTIONREGISTER";
            public const string ELEMENTMASTER = "_ELEMENTMASTER";
            public const string PACKINGTYPEMASTER = "_PACKINGTYPEMASTER";
            public const string DBBACKUP = "_DBBACKUP";
            public const string DAILYATTENDANCESHEET = "_DAILYATTENDANCESHEET";
            public const string EMPLOYEEDETAILS = "_EMPLOYEEDETAILS";
            public const string EMPLOYEEMASTER = "_EMPLOYEEMASTER";
            public const string EMPLOYEEREGISTER = "_EMPLOYEEREGISTER";
            public const string EMPLOYEESHIFTMASTER = "_EMPLOYEESHIFTMASTER";
            public const string STOREMASTER = "_STOREMASTER";

            public const string DAILYATTENDANCESHEETDUMMY = "_DAILYATTENDANCESHEETDUMMY";
            public const string REPORTPENDINGMOLD = "_REPORTPENDINGMOLD";
            public const string COREREQUIREDFORPRODUCTION = "_COREREQUIREDFORPRODUCTION";
            public const string MOLDPLAN = "_MOLDPLAN";
            public const string COREPLAN = "_COREPLAN";
            public const string OUTWARDMASTER = "_OUTWARDMASTER";
            public const string OUTWARDREGISTER = "_OUTWARDREGISTER";
            public const string INWARDMASTER = "_INWARDMASTER";
            public const string INWARDREGISTER = "_INWARDREGISTER";
            public const string PENDINGCHALLAN = "_PENDINGCHALLANREPORT";
            public const string STOREINDENTMASTER = "_STOREINDENTMASTER";
            public const string STOREINDENTREGISTER = "_STOREINDENTREGISTER";
            public const string PROCESSRIGHT = "_PROCESSRIGHT";
            public const string STOCKREPORT = "_STOCKREPORT";
            public const string BOQ = "_BOQ";
            public const string BOQREGISTER = "_BOQREGISTER";
            public const string USERWISESHORTCUT = "_USERWISESHORTCUT";
            public const string BOQREPORT = "_BOQREPORT";
            public const string EXPORTSUMMARY = "_EXPORTSUMMARY";
            public const string INVOICECASTINGMAPPING = "_INVOICECASTINGMAPPING";
            public const string HOLIDAYMASTER = "_HOLIDAYMASTER";
            public const string MONTHLYSTATUSREPORT = "_MONTHLYSTATUSREPORT";
            public const string MONTHLYSTATUSREPORTDUMMY = "_MONTHLYSTATUSREPORTDUMMY";
            public const string MOLDINGINVENTORY = "_MOLDINGINVENTORY";
            public const string SPECTROUPLOAD = "_SPECTROUPLOAD";
            public const string COREINVENTORY = "_COREINVENTORY";
            public const string DIERETIFICATIONREPORT = "_DIERETIFICATIONREPORT";
            public const string SPECTROCONFIGURATION = "_SPECTROCONFIGURATION";
            public const string NOTIFICATIONCONFIGURATION = "_NOTIFICATIONCONFIGURATION";
            public const string REPORTMOLDPLANNING = "_REPORTMOLDPLANNING";
            public const string REPORTCOREPLANNING = "_REPORTCOREPLANNING";
            public const string HEATPLANNING = "_HEATPLANNING";
            public const string REPORTHEATWISEPLANNING = "_REPORTHEATWISEPLANNING";
            public const string BACKDATELOCK = "_BACKDATELOCK";
            public const string STORERETURNMASTER = "_STORERETURNMASTER";
            public const string STORERETURNREGISTER = "_STORERETURNREGISTER";
            public const string COREMASTER = "_COREMASTER";
            public const string COREREGISTER = "_COREREGISTER";
            public const string RAWMATERIALINWARDBATCHWISE = "_RAWMATERIALINWARDBATCHWISE";
            public const string ROUTECARDMASTER = "_ROUTECARDMASTER";
            public const string PAYMENTRECEIPT = "_PAYMENTRECEIPT";
            public const string PAYMENTRECEIPTREGISTER = "_PAYMENTRECEIPTREGISTER";
            public const string PAYMENTFOLLOWUP = "_PAYMENTFOLLOWUP";
            public const string EVALUATIONCONFIGURATION = "_EVALUATIONCONFIGURATION";
            public const string PENDINGINWARD = "_PENDINGINWARD";
            public const string PURCHASESUMMARY = "_PURCHASESUMMARY";
            public const string MODIFYSTOCKRMBATCHWISE = "_MODIFYSTOCKRMBATCHWISE";
            public const string DEPARTMENTMASTER = "_DEPARTMENTMASTER";
            public const string SUPPLIEREVALUATIONREPORT = "_SUPPLIEREVALUATIONREPORT";
            public const string PARTYEMAILSETUP = "_PARTYEMAILCONFIGUARATION";
            public const string PRODUCTIONVSDISPATCH = "_PRODUCTIONVSDISPATCH";
            public const string CUSTOMERCOMPLAINT = "_CUSTOMERCOMPLAINT";
            public const string CUSTOMERCOMPLAINTREGISTER = "_CUSTOMERCOMPLAINTREGISTER";
            public const string METERREADING = "_METERREADING";
            public const string OVERHEADS = "_OVERHEADS";
            public const string DISPATCHADVICE = "_DISPATCHADVICE";
            public const string DISPATCHADVICEREGISTER = "_DISPATCHADVICEREGISTER";
            public const string CASTINGPROCESSMAPPING = "_CASTINGPROCESSMAPPING";
            public const string METERMASTER = "_METERMASTER";
            public const string REPORTITEMANALYSIS = "_REPORTITEMANALYSIS";
            public const string JOBWORKREJECTION = "_JOBWORKREJECTION";
            public const string REPORTMASTER = "_REPORTMASTER";
            public const string QCREPORT = "_QCReport";
            public const string QCREGISTER = "_QCREGISTER";
            public const string MATCHPLATEMASTER = "_MATCHPLATEMASTER";
            public const string MATCHPLATEREGISTER = "_MATCHPLATEREGISTER";
            public const string HEATCODEHISTORY = "_HEATCODEHISTORY";
            public const string DISPATCHDETAILSREPORT = "_DISPATCHDETAILSREPORT";
            public const string POWERCONSUMPTION = "_POWERCONSUMPTION";
            public const string COMPARISIONANALYSIS = "_COMPARISIONANALYSIS";
            public const string GSTTAXTEMPLATE = "_GSTTAXTEMPLATE";
            public const string HSNCODEGSTTEMPLATEMAPPING = "_HSNCODEGSTTEMPLATEMAPPING";
            public const string GSTSEQUENCE = "_GSTSEQUENCE";
            public const string AVGHEATTIME = "_AVGHEATTIME";
            public const string ACCOUNTPAYABLE = "_ACCOUNTPAYABLE";
            public const string ACCOUNTPAYABLEREGISTER = "_ACCOUNTPAYABLEREGISTER";
            public const string ACCOUNTRECEIVABLEREPORT = "_ACCOUNTRECEIVABLEREPORT";
            public const string ACCOUNTPAYABLEREPORT = "_ACCOUNTPAYABLEREPORT";
            public const string MOLDLINEMASTER = "_MOLDLINEMASTER";
            public const string OTHERCHARGEMASTER = "_OTHERCHARGEMASTER";
            public const string TAXSEQUENCETEMPLATE = "_TAXSEQUENCETEMPLATE";
            public const string SALESAMOUNTTRENDCHART = "_SALESAMOUNTTRENDCHART";
            public const string PURCHASEAMOUNTTRENDCHART = "_PURCHASEAMOUNTTRENDCHART";
            public const string DAILYPRODUCTIONCHART = "_DAILYPRODUCTIONCHART";
            public const string PRODUCTIONDIFFERANCE = "_PRODUCTIONDIFFERANCE";
            public const string BOQCONSUMPTION = "_BOQCONSUMPTION";
            public const string HEATREASON = "_HEATREASON";
            public const string PROCESSTRANSFERCHART = "_PROCESSTRANSFERDATACHART";
            public const string DAYWISEHEATCHART = "_DAYWISEHEATCHART";
            public const string PENDINGINVOICE = "_PENDINGINVOICE";
            public const string INVOICESERIES = "_INVOICESERIES";
            public const string JOBWORKPAYMENTREPORT = "_JOBWORKPAYMENTREPORT";
            public const string MATCHPLATEISSUE = "_MATCHPLATEISSUE";
            public const string MATCHPLATEISSUEREGISTER = "_MATCHPLATEISSUEREGISTER";
            public const string MATCHPLATERETURN = "_MATCHPLATERETURN";
            public const string MATCHPLATERETURNREGISTER = "_MATCHPLATERETURNREGISTER";
            public const string JOBCARDMASTER = "_JOBCARDMASTER";
            public const string JOBCARDREGISTER = "_JOBCARDREGISTER";
            public const string WAXPATTERNPRODUCTION = "_WAXPATTERNPRODUCTION";
            public const string WAXPATTERNPRODUCTIONREG = "_WAXPATTERNPRODUCTIONREGISTER";
            public const string WAXASSEMBLY = "_WAXASSEMBLY";
            public const string WAXASSEMBLYREGISTER = "_WAXASSEMBLYREGISTER";
            public const string SETUPMASTER = "_SETUPMASTER";
            public const string CASTINGSALESTRENDCHART = "_CASTINGSALESTRENDCHART";
            public const string PURCHASEVSSALESAMOUNTTRENDCHART = "_PURCHASEVSSALESAMOUNTTRENDCHART";
            public const string CASTINGPRODUCTIONTRENDCHART = "_CASTINGPRODUCTIONTRENDCHART";
            public const string WAXCHARGE = "_WAXCHARGE";
            public const string WAXSETUPPRODUCTION = "_WAXSETUPPRODUCTION";
            public const string WAXSETUPPRODUCTIONREG = "_WAXSETUPPRODUCTIONREGISTER";
            public const string WAXPATTERNSTOCKREGISTER = "_WAXPATTERNSTOCKREGISTER";
            public const string WAXSETUPSTOCKREGISTER = "_WAXSETUPSTOCKREGISTER";
            public const string MOLDINGMATERIALCONSUMPTION = "_MOLDINGMATERIALCONSUMPTION";
            public const string CASTINGPROCESSMAPPINGREGISTER = "_CASTINGPROCESSMAPPINGREGISTER";
            public const string MOLDBOXREGISTER = "_MOLDBOXREGISTER";
            public const string WAXCOATINGDETAIL = "_WAXCOATINGDETAIL";
            public const string WAXCOATINGREGISTER = "_WAXCOATINGREGISTER";
            public const string DEWAXING = "_DEWAXING";
            public const string PROCESSPERFORMREGISTER = "_PROCESSPERFORMREGISTER";
            public const string CONSUMABLEITEMUSAGE = "_CONSUMABLEITEMUSAGE";
            public const string PROCESSMOVEMENTTIMEANALYSIS = "_PROCESSMOVEMENTTIMEANALYSIS";
            public const string NOTIFICATIONLOG = "_NOTIFICATIONLOG";
            public const string REMINDERLOG = "_REMINDERLOG";
            public const string ITEMWISEPRODUCTIONREPORT = "_ITEMWISEPRODUCTIONREPORT";
            public const string ITEMWISEORDERVSDISPATCHREPORT = "_ITEMWISEORDERVSDISPATCHREPORT";
            public const string REASONWISEREJECTIONPER = "_REASONWISEREJECTIONPER";
            public const string MOLDLINEWISEPLANNINGANALYSIS = "_MOLDLINEWISEPLANNINGANALYSIS";          
            public const string LADLEMASTER = "_LADLEMASTER";
            public const string MOLDINGPROCESSMASTER = "_MOLDINGPROCESSMASTER";
            public const string COATMASTER = "_COATMASTER";
            public const string CHILLMASTER = "_CHILLMASTER";
            public const string CUSTOMERTYPECATEGORYGROUPMASTER = "_CUSTOMERTYPECATEGORYGROUPMASTER";
            public const string PURCHASEITEMTYPECATEGORYGROUPMASTER = "_PURCHASEITEMTYPECATEGORYGROUPMASTER";
            public const string PATTERNCHECKLISTMASTER = "_PATTERNCHECKLISTMASTER";
            public const string PATTERNINSPECTION = "_PATTERNINSPECTION";
            public const string SUPPLIEREVALUATION = "_SUPPLIEREVALUATION";
            public const string SUPPLIEREVALUATIONREGISTER = "_SUPPLIEREVALUATIONREGISTER";
            public const string PATTERNREWORK = "_PATTERNREWORK";
            public const string PATTERNINSPECTIONREGISTER = "_PATTERNINSPECTIONREGISTER";
            public const string PATTERNREWORKREGISTER = "_PATTERNREWORKREGISTER";
            public const string RAWMATERIALRATEHISTORY = "_RAWMATERIALRATEHISTORY";
            public const string SPREQUIREMENTMASTER = "_SPREQUIREMENTMASTER";
            public const string ORDERACCEPTANCECONFIGURATION = "_ORDERACCEPTANCECONFIGURATION";
            public const string MENUCONFIGURATION = "_MENUCONFIGURATION";
            public const string PROCESSTIMEANALYSISCHART = "_PROCESSTIMEANALYSISCHART";
            public const string MOLDLINEWISEPRODUCTINANALYSIS = "_MOLDLINEWISEPRODUCTIONANALYSIS";
            public const string MATERIALWITHEXPDATE = "_MATERIALWITHEXPDATE";
            public const string PATTERNAMORTISECOSTREPORT = "_PATTERNAMORTISECOSTREPORT";
            public const string PATTERNAGEREPORT = "_PATTERNAGEREPORT";
            public const string DOCUMENTUPLOAD = "_DOCUMENTUPLOAD";
            public const string PATTERNSHOPDEP = "_PATTERNSHOPDEP";
            public const string CASTINGROUTEMAPPING = "_CASTINGROUTEMAPPING";
            public const string MOLDSANDTYPE = "_MOLDSANDTYPE";

            public const string INSPECTIONINTIMATION = "_INSPECTIONINTIMATION";
            public const string OTHERINSPECTION = "_OTHERINSPECTION";

            public const string INSPECTIONINTIMATIONREGISTER = "_INSPECTIONINTIMATIONREGISTER";
            public const string FORMNO27C = "_FORMNO27C";
            public const string RG1REPORT = "_RG1REPORT";
            public const string RG2REPORT = "_RG2REPORT";
            public const string PATTERNLISTREPORT = "_PATTERNLISTREPORT";
            public const string INVOICECHECKLIST = "_INVOICECHECKLIST";

            public const string PENDINGBILLPASSREPORT = "_PENDINGBILLPASSREPORT";

            public const string BILLPASSREGISTER = "_BILLPASSREGISTER";

            public const string RACENTRY = "_RACENTRY";

            public const string RACREGISTER = "_RACREGISTER";
            public const string RETURNSANDMASTER = "_RETURNSANDMASTER";

            public const string MONTHLYBILLLETTER = "_MONTHLYBILLLETTER";
            public const string INHOUSEPROCESSPERFORM = "_INHOUSEPROCESSPERFORM";

            public const string ICDIEMASTER = "_ICDIEMASTER";
            public const string WAXDIEREGISTER = "_WAXDIEREGISTER";

            public const string WAXPARTPRODUCTION = "_WAXPARTPRODUCTION";
            public const string WAXPARTPRODUCTIONREGISTER = "_WAXPARTPRODUCTIONREGISTER";
            public const string DEWAXINGREGISTER = "_DEWAXINGREGISTER";
            public const string ORDERSCHEDULEREPORT = "_ORDERSCHEDULEREPORT";
            public const string INHOUSEVSPURCHASECASTINGSTOCK = "_INHOUSEVSPURCHASECASTINGSTOCK";

            public const string CASTINGWISECOMPARISONANALYSIS = "_CASTINGWISECOMPARISONANALYSIS";

            public const string PRODUCTIONVSREJECTIONTRENDCHART = "_PRODUCTIONVSREJECTIONTRENDCHART";
            public const string GRADEWISEMELTINGCOST = "_GRADEWISEMELTINGCOST";
            public const string CHEMICALANALYSISREPORT = "_CHEMICALANALYSISREPORT";

            public const string SIGNATURECONFIG = "_SIGNATURECONFIG";
            public const string MPINSPECTIONENTRY = "_MPINSPECTIONENTRY";

            public const string DPINSPECTIONENTRY = "_DPINSPECTIONENTRY";
            public const string MPINSPECTIONREGISTER = "_MPINSPECTIONREGISTER";
            public const string DPINSPECTIONREGISTER = "_DPINSPECTIONREGISTER";
            public const string MPTESTCERTIFICATE = "_MPTESTCERTIFICATE";

            public const string DPTESTCERTIFICATE = "_DPTESTCERTIFICATE";
            public const string HEATTREATMENT = "_HEATTREATMENT";
            public const string HEATTREATMENTREGISTER = "_HEATTREATMENTREGISTER";

            public const string DPTESTCERIFICATEREGISTER = "_DPTESTCERIFICATEREGISTER";

            public const string MPTESTCERIFICATEREGISTER = "_MPTESTCERIFICATEREGISTER";

            public const string SUPPLIERAPPROVALCRITERIA = "_SUPPLIERAPPROVALCRITERIA";

            public const string MATERIALSAMPLEINSPECTION = "_MATERIALSAMPLEINSPECTION";
            public const string MATERIALSAMPLEINSPECTIONREGISTER = "_MATERIALSAMPLEINSPECTIONREGISTER";
            public const string MATERIALFORWARDINGNOTEREGISTER = "_MATERIALFORWARDINGNOTEREGISTER";


            public const string INHOUSEMSPROCESSPERFORM = "_INHOUSEMSPROCESSPERFORM";

            public const string CRITERIATEMPLATE = "_CRITERIATEMPLATE";
            public const string REWORKPROCESS = "_REWORKPROCESS";
            public const string MACHINEIDEALTIMEREPORT = "_MACHINEIDEALTIMEREPORT";
            public const string MSREGISTER = "_MSREGISTER";
            


            //Properties For Getter setter for Menu Ended

        }
    }
}

